[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "anu-ctlab-io"
version = "0.0.1"
description = "python I/O for the ANU CTLab array storage format(s)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "xarray>=2025.1.2",
]

[dependency-groups]
dev = [
    "pre-commit>=4.1.0",
    "ruff>=0.9.5",
    "pytest>=8.3.5",
    "dask>=2025.2.0",
    "netcdf4>=1.7.2",
    "numpy>=2.2.3",
]
