name: publish

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.3"
      - name: Build source distribution
        run: uv build
      - uses: actions/upload-artifact@v4
        with:
          name: test-pypi-files-sdist
          path: dist

  testpypi-publish:
    name: "build and publish release"
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: testpypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v5
        with:
          pattern: test-pypi-files-*
          merge-multiple: true
          path: dist/
      - run: ls -lh dist/
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
